---
all:
  vars:
    ansible_user: dev_user
    ansible_ssh_private_key_file: ~/.ssh/dev_key.pem
  children:
    api-gateway:
      hosts:
        dev-api-gateway-1:
          ansible_host: 192.168.1.10
    eureka-server:
      hosts:
        dev-eureka-server-1:
          ansible_host: 192.168.1.11
    user-service:
      hosts:
        dev-user-service-1:
          ansible_host: 192.168.1.12
    payment-service:
      hosts:
        dev-payment-service-1:
          ansible_host: 192.168.1.13
    notification-service:
      hosts:
        dev-notification-service-1:
          ansible_host: 192.168.1.14
    frontend:
      hosts:
        dev-frontend-1:
          ansible_host: 192.168.1.15
