---
all:
  vars:
    ansible_user: staging_user
    ansible_ssh_private_key_file: ~/.ssh/staging_key.pem
  children:
    api-gateway:
      hosts:
        staging-api-gateway-1:
          ansible_host: 192.168.2.10
    eureka-server:
      hosts:
        staging-eureka-server-1:
          ansible_host: 192.168.2.11
    user-service:
      hosts:
        staging-user-service-1:
          ansible_host: 192.168.2.12
    payment-service:
      hosts:
        staging-payment-service-1:
          ansible_host: 192.168.2.13
    notification-service:
      hosts:
        staging-notification-service-1:
          ansible_host: 192.168.2.14
    frontend:
      hosts:
        staging-frontend-1:
          ansible_host: 192.168.2.15
